---
title: "Quiz4"
author: "kwatanwa17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1
```{r}
library(MASS)
data(shuttle)

## Make our own variables just for illustration
shuttle$auto <- 1 * (shuttle$use == "auto")
shuttle$headwind <- 1 * (shuttle$wind == "head")
shuttle
fit <- glm(auto ~ headwind, data = shuttle, family = binomial)
coef(fit)

## Another way without redifing variables
fit <- glm(relevel(use, "noauto") ~ relevel(wind, "tail"), data = shuttle, family = binomial)

exp(coef(fit))

```

##2
```{r}
shuttle$auto <- 1 * (shuttle$use == "auto")
shuttle$headwind <- 1 * (shuttle$wind == "head")
fit <- glm(auto ~ headwind + magn, data = shuttle, family = binomial)
exp(coef(fit))

#adjusting for wind strength

## Another way without redifing variables
fit <- glm(relevel(use, "noauto") ~ relevel(wind, "tail") + magn, data = shuttle, 
    family = binomial)
exp(coef(fit))
```

## 3
```{r}
#If you fit a logistic regression model to a binary variable, for example use of the autolander, then fit a logistic regression model for one minus the outcome (not using the autolander) what happens to the coefficients?

fit1 <- glm(auto ~ headwind, data = shuttle, family = binomial)

fit2 <- glm(I(1- auto) ~ headwind, data = shuttle, family = binomial)

summary(fit1)
summary(fit2)

#Inverse the sign

#The intercept changes sign, but the other coefficients don't. no
#linear fashion no
```

## 4
```{r}
fit <- glm(count ~ relevel(spray, "B"), data = InsectSprays, family = poisson) #spray B as denominatorq
summary(fit)
fit$coef
exp(coef(fit))
exp(coef(fit))[2]
```

## 5
```{r}
#Question 5
#Consider a Poisson glm with an offset, tt. So, for example, a model of the form \verb|glm(count ~ x + offset(t), family = poisson)|glm(count x+offset(t),family=poisson) where \verb|x|x is a factor variable comparing a treatment (1) to a control (0) and \verb|t|t is the natural log of a monitoring time. What is impact of the coefficient for \verb|x|x if we fit the model \verb|glm(count ~ x + offset(t2), family = poisson)|glm(count x+offset(t2),family=poisson) where \verb|2 <- log(10) + t|2<-log(10)+t? In other words, what happens to the coefficients if we change the units of the offset variable. (Note, adding log(10) on the log scale is multiplying by 10 on the original scale.)
t <- runif(100)
x <- rep(c(1,0),50)
a <- glm(count ~ x + offset(t),family=poisson)
b <- glm(count ~ x + offset(t2),family=poisson)
t2 <- *10t
#The coefficient estimate is divided by 10. or multiplied noo
#Not change?
```

## 6
```{r}
x <- -5:5
y <- c(5.12, 3.93, 2.67, 1.87, 0.52, 0.08, 0.93, 2.05, 2.54, 3.87, 4.97)

z <- (x > 0) * x
fit <- lm(y ~ x + z)
coef(fit)
sum(coef(fit)[2:3])

```
